# fly.toml app configuration file generated for countdowns on 2023-10-13T17:09:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "countdowns"
primary_region = "otp"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "7.4"

[env]
  APP_ENV = "production"
  APP_URL = "https://countdowns.fly.dev"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION="sqlite"
  DB_DATABASE="/var/www/html/database/database.sqlite"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]